CREATE TABLE `PERSONS` (
	`ID` INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	`FIRSTNAME` VARCHAR(50) NULL DEFAULT NULL,
	`LASTNAME` VARCHAR(50) NULL DEFAULT NULL,
	`ADDRESS` VARCHAR(200) NULL DEFAULT NULL,
	`GENDER` VARCHAR(10) NULL DEFAULT NULL
)
ENGINE = INNODB;